//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class choice
    {
        public int choice_ID { get; set; }
        public string choice_desc { get; set; }
        public string isCorrect { get; set; }
        public int q_ID { get; set; }
    
        public virtual question question { get; set; }
    }
}
