//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Student
    {
        public int St_ID { get; set; }
        public int Exam_ID { get; set; }
        public Nullable<int> st_grade { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual student student { get; set; }
    }
}
