//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class exams_questions
    {
        public int exam_ID { get; set; }
        public int q_ID { get; set; }
        public Nullable<int> answer { get; set; }
        public int St_ID { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual question question { get; set; }
        public virtual student student { get; set; }
    }
}
