//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sqlProjectEntities : DbContext
    {
        public sqlProjectEntities()
            : base("name=sqlProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<choice> choices { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<Exam_Student> Exam_Student { get; set; }
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<exams_questions> exams_questions { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<topic> topics { get; set; }
    
        public virtual int choices_delete(Nullable<int> ch_id)
        {
            var ch_idParameter = ch_id.HasValue ?
                new ObjectParameter("ch_id", ch_id) :
                new ObjectParameter("ch_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("choices_delete", ch_idParameter);
        }
    
        public virtual int choices_insert(Nullable<int> chID, string desc, string iscorrect, Nullable<int> q_id)
        {
            var chIDParameter = chID.HasValue ?
                new ObjectParameter("chID", chID) :
                new ObjectParameter("chID", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var iscorrectParameter = iscorrect != null ?
                new ObjectParameter("iscorrect", iscorrect) :
                new ObjectParameter("iscorrect", typeof(string));
    
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("choices_insert", chIDParameter, descParameter, iscorrectParameter, q_idParameter);
        }
    
        public virtual ObjectResult<choices_select_Result> choices_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<choices_select_Result>("choices_select");
        }
    
        public virtual int choices_update(Nullable<int> chID, string desc, string iscorrect, Nullable<int> q_id)
        {
            var chIDParameter = chID.HasValue ?
                new ObjectParameter("chID", chID) :
                new ObjectParameter("chID", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var iscorrectParameter = iscorrect != null ?
                new ObjectParameter("iscorrect", iscorrect) :
                new ObjectParameter("iscorrect", typeof(string));
    
            var q_idParameter = q_id.HasValue ?
                new ObjectParameter("q_id", q_id) :
                new ObjectParameter("q_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("choices_update", chIDParameter, descParameter, iscorrectParameter, q_idParameter);
        }
    
        public virtual int courses_delete(Nullable<int> cID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("cID", cID) :
                new ObjectParameter("cID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("courses_delete", cIDParameter);
        }
    
        public virtual int courses_insert(Nullable<int> cID, string cName)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("cID", cID) :
                new ObjectParameter("cID", typeof(int));
    
            var cNameParameter = cName != null ?
                new ObjectParameter("cName", cName) :
                new ObjectParameter("cName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("courses_insert", cIDParameter, cNameParameter);
        }
    
        public virtual ObjectResult<courses_select_Result> courses_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<courses_select_Result>("courses_select");
        }
    
        public virtual int courses_update(Nullable<int> cID, string cName)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("cID", cID) :
                new ObjectParameter("cID", typeof(int));
    
            var cNameParameter = cName != null ?
                new ObjectParameter("cName", cName) :
                new ObjectParameter("cName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("courses_update", cIDParameter, cNameParameter);
        }
    
        public virtual int Department_Delete(string col_Name, string value)
        {
            var col_NameParameter = col_Name != null ?
                new ObjectParameter("Col_Name", col_Name) :
                new ObjectParameter("Col_Name", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Department_Delete", col_NameParameter, valueParameter);
        }
    
        public virtual int Department_Insert(Nullable<int> dept_ID, string dept_Name, Nullable<int> manager_ID)
        {
            var dept_IDParameter = dept_ID.HasValue ?
                new ObjectParameter("Dept_ID", dept_ID) :
                new ObjectParameter("Dept_ID", typeof(int));
    
            var dept_NameParameter = dept_Name != null ?
                new ObjectParameter("Dept_Name", dept_Name) :
                new ObjectParameter("Dept_Name", typeof(string));
    
            var manager_IDParameter = manager_ID.HasValue ?
                new ObjectParameter("Manager_ID", manager_ID) :
                new ObjectParameter("Manager_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Department_Insert", dept_IDParameter, dept_NameParameter, manager_IDParameter);
        }
    
        public virtual ObjectResult<Department_Select_Result> Department_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Department_Select_Result>("Department_Select");
        }
    
        public virtual int Department_Update(string col_Name, string old_Value, string new_Value)
        {
            var col_NameParameter = col_Name != null ?
                new ObjectParameter("Col_Name", col_Name) :
                new ObjectParameter("Col_Name", typeof(string));
    
            var old_ValueParameter = old_Value != null ?
                new ObjectParameter("Old_Value", old_Value) :
                new ObjectParameter("Old_Value", typeof(string));
    
            var new_ValueParameter = new_Value != null ?
                new ObjectParameter("New_Value", new_Value) :
                new ObjectParameter("New_Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Department_Update", col_NameParameter, old_ValueParameter, new_ValueParameter);
        }
    
        public virtual int exams_delete(Nullable<int> exID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_delete", exIDParameter);
        }
    
        public virtual int exams_insert(Nullable<int> exID, Nullable<int> courseId)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_insert", exIDParameter, courseIdParameter);
        }
    
        public virtual int exams_qu_delete(Nullable<int> exID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_qu_delete", exIDParameter);
        }
    
        public virtual int exams_qu_insert(Nullable<int> exID, Nullable<int> qID, Nullable<int> answer, Nullable<int> stdID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("qID", qID) :
                new ObjectParameter("qID", typeof(int));
    
            var answerParameter = answer.HasValue ?
                new ObjectParameter("answer", answer) :
                new ObjectParameter("answer", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_qu_insert", exIDParameter, qIDParameter, answerParameter, stdIDParameter);
        }
    
        public virtual ObjectResult<exams_qu_select_Result> exams_qu_select(Nullable<int> exID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exams_qu_select_Result>("exams_qu_select", exIDParameter);
        }
    
        public virtual int exams_qu_update(Nullable<int> exID, Nullable<int> qID, string answer, Nullable<int> stdID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("qID", qID) :
                new ObjectParameter("qID", typeof(int));
    
            var answerParameter = answer != null ?
                new ObjectParameter("answer", answer) :
                new ObjectParameter("answer", typeof(string));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_qu_update", exIDParameter, qIDParameter, answerParameter, stdIDParameter);
        }
    
        public virtual ObjectResult<exams_select_Result> exams_select(Nullable<int> exID)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<exams_select_Result>("exams_select", exIDParameter);
        }
    
        public virtual int exams_update(Nullable<int> exID, Nullable<int> courseId)
        {
            var exIDParameter = exID.HasValue ?
                new ObjectParameter("exID", exID) :
                new ObjectParameter("exID", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("exams_update", exIDParameter, courseIdParameter);
        }
    
        public virtual ObjectResult<finalResult_Result> finalResult(Nullable<int> std_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<finalResult_Result>("finalResult", std_idParameter);
        }
    
        public virtual int ins_courseDelete(Nullable<int> s_id, Nullable<int> c_id)
        {
            var s_idParameter = s_id.HasValue ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(int));
    
            var c_idParameter = c_id.HasValue ?
                new ObjectParameter("c_id", c_id) :
                new ObjectParameter("c_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_courseDelete", s_idParameter, c_idParameter);
        }
    
        public virtual ObjectResult<ins_Courseselect_Result> ins_Courseselect(Nullable<int> s_id, Nullable<int> c_id)
        {
            var s_idParameter = s_id.HasValue ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(int));
    
            var c_idParameter = c_id.HasValue ?
                new ObjectParameter("c_id", c_id) :
                new ObjectParameter("c_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ins_Courseselect_Result>("ins_Courseselect", s_idParameter, c_idParameter);
        }
    
        public virtual int ins_courseupdate(Nullable<int> s_id, Nullable<int> c_id)
        {
            var s_idParameter = s_id.HasValue ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(int));
    
            var c_idParameter = c_id.HasValue ?
                new ObjectParameter("c_id", c_id) :
                new ObjectParameter("c_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_courseupdate", s_idParameter, c_idParameter);
        }
    
        public virtual int instructor_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("instructor_delete", idParameter);
        }
    
        public virtual int instructor_insert(Nullable<int> id, string name, string username, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("instructor_insert", idParameter, nameParameter, usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<instructor_select_Result> instructor_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<instructor_select_Result>("instructor_select");
        }
    
        public virtual int instructor_update(Nullable<int> id, string name, string username, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("instructor_update", idParameter, nameParameter, usernameParameter, passwordParameter);
        }
    
        public virtual int Questions_Delete(Nullable<int> qID)
        {
            var qIDParameter = qID.HasValue ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Questions_Delete", qIDParameter);
        }
    
        public virtual int Questions_Insert(Nullable<int> ques_ID, string ques_Desc, string ques_Type, Nullable<int> course_ID)
        {
            var ques_IDParameter = ques_ID.HasValue ?
                new ObjectParameter("Ques_ID", ques_ID) :
                new ObjectParameter("Ques_ID", typeof(int));
    
            var ques_DescParameter = ques_Desc != null ?
                new ObjectParameter("Ques_Desc", ques_Desc) :
                new ObjectParameter("Ques_Desc", typeof(string));
    
            var ques_TypeParameter = ques_Type != null ?
                new ObjectParameter("Ques_Type", ques_Type) :
                new ObjectParameter("Ques_Type", typeof(string));
    
            var course_IDParameter = course_ID.HasValue ?
                new ObjectParameter("Course_ID", course_ID) :
                new ObjectParameter("Course_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Questions_Insert", ques_IDParameter, ques_DescParameter, ques_TypeParameter, course_IDParameter);
        }
    
        public virtual ObjectResult<Questions_Select_Result> Questions_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Questions_Select_Result>("Questions_Select");
        }
    
        public virtual int Questions_Update(string col_Name, string old_Value, string new_Value)
        {
            var col_NameParameter = col_Name != null ?
                new ObjectParameter("Col_Name", col_Name) :
                new ObjectParameter("Col_Name", typeof(string));
    
            var old_ValueParameter = old_Value != null ?
                new ObjectParameter("Old_Value", old_Value) :
                new ObjectParameter("Old_Value", typeof(string));
    
            var new_ValueParameter = new_Value != null ?
                new ObjectParameter("New_Value", new_Value) :
                new ObjectParameter("New_Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Questions_Update", col_NameParameter, old_ValueParameter, new_ValueParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int studCourse_delete(Nullable<int> st_id)
        {
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studCourse_delete", st_idParameter);
        }
    
        public virtual int studCourse_insert(Nullable<int> st_id, Nullable<int> course_id)
        {
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studCourse_insert", st_idParameter, course_idParameter);
        }
    
        public virtual ObjectResult<studCourse_select_Result> studCourse_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<studCourse_select_Result>("studCourse_select");
        }
    
        public virtual int studCourse_update(Nullable<int> st_id, Nullable<int> course_id)
        {
            var st_idParameter = st_id.HasValue ?
                new ObjectParameter("st_id", st_id) :
                new ObjectParameter("st_id", typeof(int));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studCourse_update", st_idParameter, course_idParameter);
        }
    
        public virtual int students_delete(Nullable<int> stdID)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("students_delete", stdIDParameter);
        }
    
        public virtual int students_insert(Nullable<int> stdID, string stdFname, string stdLname, Nullable<int> deptID, string username, string pw)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            var stdFnameParameter = stdFname != null ?
                new ObjectParameter("stdFname", stdFname) :
                new ObjectParameter("stdFname", typeof(string));
    
            var stdLnameParameter = stdLname != null ?
                new ObjectParameter("stdLname", stdLname) :
                new ObjectParameter("stdLname", typeof(string));
    
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("students_insert", stdIDParameter, stdFnameParameter, stdLnameParameter, deptIDParameter, usernameParameter, pwParameter);
        }
    
        public virtual ObjectResult<students_select_Result> students_select(Nullable<int> stdID)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<students_select_Result>("students_select", stdIDParameter);
        }
    
        public virtual int students_update(Nullable<int> stdID, string stdFname, string stdLname, Nullable<int> deptID, string username, string pw)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            var stdFnameParameter = stdFname != null ?
                new ObjectParameter("stdFname", stdFname) :
                new ObjectParameter("stdFname", typeof(string));
    
            var stdLnameParameter = stdLname != null ?
                new ObjectParameter("stdLname", stdLname) :
                new ObjectParameter("stdLname", typeof(string));
    
            var deptIDParameter = deptID.HasValue ?
                new ObjectParameter("deptID", deptID) :
                new ObjectParameter("deptID", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("students_update", stdIDParameter, stdFnameParameter, stdLnameParameter, deptIDParameter, usernameParameter, pwParameter);
        }
    
        public virtual int topic_delete(Nullable<int> topic_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("topic_delete", topic_idParameter);
        }
    
        public virtual int topic_insert(Nullable<int> topic_id, string topic_name, Nullable<int> course_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var topic_nameParameter = topic_name != null ?
                new ObjectParameter("topic_name", topic_name) :
                new ObjectParameter("topic_name", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("topic_insert", topic_idParameter, topic_nameParameter, course_idParameter);
        }
    
        public virtual ObjectResult<topic_select_Result> topic_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<topic_select_Result>("topic_select");
        }
    
        public virtual int topic_update(Nullable<int> topic_id, string topic_name, Nullable<int> course_id)
        {
            var topic_idParameter = topic_id.HasValue ?
                new ObjectParameter("topic_id", topic_id) :
                new ObjectParameter("topic_id", typeof(int));
    
            var topic_nameParameter = topic_name != null ?
                new ObjectParameter("topic_name", topic_name) :
                new ObjectParameter("topic_name", typeof(string));
    
            var course_idParameter = course_id.HasValue ?
                new ObjectParameter("course_id", course_id) :
                new ObjectParameter("course_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("topic_update", topic_idParameter, topic_nameParameter, course_idParameter);
        }
    
        public virtual int AssignExamStudent(Nullable<int> examid, Nullable<int> stdID)
        {
            var examidParameter = examid.HasValue ?
                new ObjectParameter("examid", examid) :
                new ObjectParameter("examid", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AssignExamStudent", examidParameter, stdIDParameter);
        }
    
        public virtual int correctExam(Nullable<int> examID, Nullable<int> stdID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("examID", examID) :
                new ObjectParameter("examID", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("correctExam", examIDParameter, stdIDParameter);
        }
    
        public virtual int examAns(Nullable<int> examID, Nullable<int> stID, Nullable<int> q1, Nullable<int> q2, Nullable<int> q3, Nullable<int> q4, Nullable<int> q5, Nullable<int> q6, Nullable<int> q7, Nullable<int> q8, Nullable<int> q9, Nullable<int> q10)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("examID", examID) :
                new ObjectParameter("examID", typeof(int));
    
            var stIDParameter = stID.HasValue ?
                new ObjectParameter("stID", stID) :
                new ObjectParameter("stID", typeof(int));
    
            var q1Parameter = q1.HasValue ?
                new ObjectParameter("q1", q1) :
                new ObjectParameter("q1", typeof(int));
    
            var q2Parameter = q2.HasValue ?
                new ObjectParameter("q2", q2) :
                new ObjectParameter("q2", typeof(int));
    
            var q3Parameter = q3.HasValue ?
                new ObjectParameter("q3", q3) :
                new ObjectParameter("q3", typeof(int));
    
            var q4Parameter = q4.HasValue ?
                new ObjectParameter("q4", q4) :
                new ObjectParameter("q4", typeof(int));
    
            var q5Parameter = q5.HasValue ?
                new ObjectParameter("q5", q5) :
                new ObjectParameter("q5", typeof(int));
    
            var q6Parameter = q6.HasValue ?
                new ObjectParameter("q6", q6) :
                new ObjectParameter("q6", typeof(int));
    
            var q7Parameter = q7.HasValue ?
                new ObjectParameter("q7", q7) :
                new ObjectParameter("q7", typeof(int));
    
            var q8Parameter = q8.HasValue ?
                new ObjectParameter("q8", q8) :
                new ObjectParameter("q8", typeof(int));
    
            var q9Parameter = q9.HasValue ?
                new ObjectParameter("q9", q9) :
                new ObjectParameter("q9", typeof(int));
    
            var q10Parameter = q10.HasValue ?
                new ObjectParameter("q10", q10) :
                new ObjectParameter("q10", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("examAns", examIDParameter, stIDParameter, q1Parameter, q2Parameter, q3Parameter, q4Parameter, q5Parameter, q6Parameter, q7Parameter, q8Parameter, q9Parameter, q10Parameter);
        }
    
        public virtual int generateExam(string courseName, Nullable<int> tFnum, Nullable<int> mcqNum)
        {
            var courseNameParameter = courseName != null ?
                new ObjectParameter("courseName", courseName) :
                new ObjectParameter("courseName", typeof(string));
    
            var tFnumParameter = tFnum.HasValue ?
                new ObjectParameter("TFnum", tFnum) :
                new ObjectParameter("TFnum", typeof(int));
    
            var mcqNumParameter = mcqNum.HasValue ?
                new ObjectParameter("mcqNum", mcqNum) :
                new ObjectParameter("mcqNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("generateExam", courseNameParameter, tFnumParameter, mcqNumParameter);
        }
    
        public virtual ObjectResult<finalResults_Result> finalResults(Nullable<int> std_id)
        {
            var std_idParameter = std_id.HasValue ?
                new ObjectParameter("std_id", std_id) :
                new ObjectParameter("std_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<finalResults_Result>("finalResults", std_idParameter);
        }
    
        public virtual ObjectResult<Report_3_Result> Report_3(Nullable<int> inst_Id)
        {
            var inst_IdParameter = inst_Id.HasValue ?
                new ObjectParameter("inst_Id", inst_Id) :
                new ObjectParameter("inst_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_3_Result>("Report_3", inst_IdParameter);
        }
    
        public virtual ObjectResult<report_studentInfo_Result> report_studentInfo(Nullable<int> depID)
        {
            var depIDParameter = depID.HasValue ?
                new ObjectParameter("depID", depID) :
                new ObjectParameter("depID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_studentInfo_Result>("report_studentInfo", depIDParameter);
        }
    
        public virtual ObjectResult<report_courseTopics_Result> report_courseTopics(Nullable<int> cID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("cID", cID) :
                new ObjectParameter("cID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_courseTopics_Result>("report_courseTopics", cIDParameter);
        }
    
        public virtual ObjectResult<report_StudentExMA_Result> report_StudentExMA(Nullable<int> examID, Nullable<int> studID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(int));
    
            var studIDParameter = studID.HasValue ?
                new ObjectParameter("StudID", studID) :
                new ObjectParameter("StudID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_StudentExMA_Result>("report_StudentExMA", examIDParameter, studIDParameter);
        }
    
        public virtual ObjectResult<ExamStudents_Result> ExamStudents(Nullable<int> eID)
        {
            var eIDParameter = eID.HasValue ?
                new ObjectParameter("EID", eID) :
                new ObjectParameter("EID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExamStudents_Result>("ExamStudents", eIDParameter);
        }
    
        public virtual ObjectResult<report_examQandA_Result> report_examQandA(Nullable<int> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("examID", examID) :
                new ObjectParameter("examID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_examQandA_Result>("report_examQandA", examIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ExamCoursesStudents(Nullable<int> cID, Nullable<int> sID)
        {
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("CID", cID) :
                new ObjectParameter("CID", typeof(int));
    
            var sIDParameter = sID.HasValue ?
                new ObjectParameter("SID", sID) :
                new ObjectParameter("SID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ExamCoursesStudents", cIDParameter, sIDParameter);
        }
    
        public virtual int ins_courseInsert(Nullable<int> s_id, Nullable<int> c_id)
        {
            var s_idParameter = s_id.HasValue ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(int));
    
            var c_idParameter = c_id.HasValue ?
                new ObjectParameter("c_id", c_id) :
                new ObjectParameter("c_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_courseInsert", s_idParameter, c_idParameter);
        }
    
        public virtual int dept_coursesInsert(Nullable<int> dID, Nullable<int> cID)
        {
            var dIDParameter = dID.HasValue ?
                new ObjectParameter("DID", dID) :
                new ObjectParameter("DID", typeof(int));
    
            var cIDParameter = cID.HasValue ?
                new ObjectParameter("CID", cID) :
                new ObjectParameter("CID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dept_coursesInsert", dIDParameter, cIDParameter);
        }
    }
}
